### ISSUE TITLE
The Problem of setting threshold of discrete emotions

### ISSUE THREAD

**Issue by RyanShun-511** [Tandon-A/emotic#18]
According to the paper, the threshold of discrete emotion recognition is set as Precision=Recall. Why is it set like this? How did you get this value? Did you get it through training?
What do the values of the elements [1,26] represent when you enter a picture? It doesn't mean accuracy, does it? 
I am a novice, hope to get your answer, thank you!

**Comment by RyanShun-511** [comment]
@Tandon-A

**Comment by Tandon-A** [comment]
@RyanShun-511 

Hello, 

My apologies for the delay. 

Here we are considering 26 discrete emotion categories. 
During model training, we present the model with an image and its target emotions as an array of 26 elements, where the target emotions have their value set to 1 and other values are zero. 

For example, consider three emotions: Angry, Happy, and Sad. For three emotions we create the target array of 3 elements, where the elements are in the order of these emotions. 
For Image 1, which is a 'Happy' image, the target array becomes -> [0, 1, 0]
For Image 2, which is a 'Angry' and 'Sad' image, the target array becomes -> [1, 0, 1]
For Image 3, which is a 'Sad' image, the target array becomes -> [0, 0, 1]

The model is thus trained to determine the probability of each emotion category in the image. These output probabilities lie in the range of [0, 1]. This is the value of elements [1,26]. 
Consider the same example from above. 
For Image 1, which is a 'Happy' image, the model could output -> [0.1, 0.8, 0.05]
For Image 2, which is a 'Angry' and 'Sad' image, the model could output -> [0.76, 0.2, 0.65]
For Image 3, which is a 'Sad' image, the model could output -> [0.55, 0.19, 0.82]

But to obtain discrete emotion categories given a picture, we need a way to convert these probabilities to 1 or 0, 1 denoting that the image has that emotion and 0 otherwise. Here, we use thresholds. 

One simple thresholding approach could be just to threshold the values at 0.5 following the rule below:
If emotion probability > 0.5 -> Image has that specific emotion, 
else -> Image does not have that specific emotion 
Following this rule for our example cases, 
For Image 1, which is a 'Happy' image, the thresholded values become -> [0, 1, 0] 
For Image 2, which is a 'Angry' and 'Sad' image, the thresholded values become -> [1, 0, 1]
For Image 3, which is a 'Sad' image, the thresholded values become -> [ 1, 0, 1] 
Comparing these thresholded values with the label arrays we can see that Image 3 has been wrongly classified as Angry. 
Also, by increasing the threshold value to 0.6, we can see that we will filter out the 0.55 probability in the third example, leading to correct classification. 

Increasing/decreasing threshold values will thus impact the Precision and Recall values. 
In the general case, we don't have any preference between the two, so we select the threshold value where Precision == Recall. 

If you have a specific case where you just cannot give a wrong emotion category prediction, then you need to prioritize Precision and select a threshold accordingly. Similarly, when you need to optimize for Recall, you can experiment with different threshold values. 

Do note, that in the simple thresholding approach (filtering by 0.5) we use the same threshold for all emotion categories. But using the thresholds from Precision == Recall, allows us to use different thresholds for each category, thus allowing to optimize for our general case. 

I hope this answers your question. 

Regards, 
Abhishek

**Comment by Tandon-A** [comment]
@RyanShun-511 

This might also help. https://github.com/Tandon-A/emotic/issues/2

**Comment by Tandon-A** [comment]
@RyanShun-511 

Please feel free to reopen the issue.
